name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - "package.json"    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: niradler/statikly
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        platform: linux/amd64,linux/arm64,linux/arm/v7